#!/bin/sh

#if file does not exist, create it
if [ ! -f $HOME/.cache/daily-todo.txt ]; then
    touch $HOME/.cache/daily-todo.txt
fi

values(){
    printf "30 minutes CS50 course\n"
    printf "30 minutes Trailhead\n"
}
values > $HOME/.cache/daily-todo.txt
