#!/bin/bash 
case $BLOCK_BUTTON in
    1) $TERMINAL -e pulsemixer;;
    3) pamixer -t ;;
    4) pamixer -i 5;;
    5) pamixer -d 5;;
esac
vol="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)].*/\1/')";
if [ "$vol" = "off" ]; then
	echo $vol
else
	vol="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
	echo "${vol}%"
fi
