#!/bin/bash

ffmpeg -ss 11:47 -to 12:32 -i $(youtube-dl -f bestvideo -g "https://www.youtube.com/watch?v=wRNzpb97cNs&t=625s") -ss 11:47 -to 12:32 -i $(youtube-dl -f bestaudio -g "https://www.youtube.com/watch?v=wRNzpb97cNs&t=625s") -c copy output.mp4
