#!/bin/sh

# add more args here according to preference

notification(){
# change the icon to whatever you want. Make sure your notification server 
# supports it and already configured.

# Now it will receive argument so the user can rename the radio title
# to whatever they want

	notify-send "Playing now: " "$@" --icon=media-tape
}

menu(){
	printf "1. Reboot\n"
	printf "2. PowerOff\n"
	printf "3. Lock\n"
}

main() {
	choice=$(menu | rofi -dmenu | cut -d. -f1)

	case $choice in
		1)
            notification "Powering off in 10 seconds";
            sleep 20;
            reboot;
			break
			;;
		2)
            notification " Powering off in 20 seconds";
            sleep 20;
            poweroff;
			break
			;;
		3)
            notification " Locking in  5 seconds";
            sleep 5;
            i3lock-fancy;
			break
			;;
    esac
}
main
