#!/bin/sh

# add more args here according to preference
ARGS="--volume=80"

notification(){
# change the icon to whatever you want. Make sure your notification server
# supports it and already configured.

# Now it will receive argument so the user can rename the radio title
# to whatever they want

	notify-send "Playing now: " "$@" --icon=media-tape
}

menu(){
    printf "0. English Radio\n"
	printf "1. Lofi Girl\n"
	printf "2. Chillhop\n"
	printf "3. Box Lofi\n"
	printf "4. The Bootleg Boy\n"
	printf "5. Radio Spinner\n"
	printf "6. SmoothChill\n"
    printf "7. Indian Classic\n"
    printf "8. Indian Songs\n"
    printf "9. Misc\n"
    printf "10. Best\n"
    printf "11. Chill EDM\n"
    printf "12. Chill English\n"
    printf "13. namaste Bollywood\n"
}

main() {
	choice=$(menu | rofi -dmenu -font 'Fira Code 18'| cut -d. -f1)

	case $choice in
		0)
			notification "English Radio ☕️🎶";
            URL="https://16803.live.streamtheworld.com/977_HITSAAC_SC"
			break
			;;
		1)
			notification "Lofi Girl ☕️🎶";
            URL="https://play.streamafrica.net/lofiradio"
			break
			;;
		2)
			notification "Chillhop ☕️🎶";
            URL="http://stream.zeno.fm/fyn8eh3h5f8uv"
			break
			;;
		3)
			notification "Box Lofi ☕️🎶";
            URL="http://stream.zeno.fm/f3wvbbqmdg8uv"
			break
			;;
		4)
			notification "The Bootleg Boy ☕️🎶";
            URL="http://stream.zeno.fm/0r0xa792kwzuv"
			break
			;;
		5)
			notification "Radio Spinner ☕️🎶";
            URL="https://live.radiospinner.com/lofi-hip-hop-64"
			break
			;;
		6)
			notification "SmoothChill ☕️🎶";
            URL="https://media-ssl.musicradio.com/SmoothChill"
			break
			;;
		7)
			notification "Indian Classic☕️🎶";
            URL="http://stream.globalic.com.ua:1060/stream"
			break
			;;
		8)
			notification "Indian songs ☕️🎶";
            URL="https://indianlink.radioca.st/streams/128kbps?yp=2"
			break
			;;
		9)
			notification "Misc ☕️🎶";
            URL="http://eu10.fastcast4u.com:5040/stream"
			break
			;;
		10)
			notification "Best ☕️🎶";
            URL="http://i6.streams.ovh:16052/autodj"
			break
			;;
		11)
			notification "Chill EDm ☕️🎶";
            URL="http://node-11.zeno.fm/2d3yxh6fd2zuv?rj-ttl=5&rj-tok=AAABfLZGTdcA7SLrTet-qycCFQ"
			break
			;;
		12)
			notification "Chill English ☕️🎶";
            URL="https://d1qg6pckcqcdk0.cloudfront.net/easy/brucemarie_moonchants_16_songofthesnowqueenwinter.m4a"
			break
			;;
		13)
			notification "Namaste Bollywood☕️🎶";
            URL="https://stream.zeno.fm/cqak4ap7by8uv"
			break
			;;
	esac
    # run mpv with args and selected url
    # added title arg to make sure the pkill command kills only this instance of mpv
    mpv $ARGS --title="radio-mpv" $URL
}

pkill -f radio-mpv || main
