#!/bin/sh


notification(){
	# notify-send "Playing now: " "$@" --icon=media-tape
    echo "test"
}

menu(){
    printf "0. Sleep\n"
	printf "1. Reboot\n"
	printf "2. PowerOff\n"
	printf "3. Lock\n"
}

main() {
	choice=$(menu | rofi -i -dmenu | cut -d. -f1)

	case $choice in
        0)
            notification "Sleeping in 10 seconds"
            # sleep 10
            systemctl suspend
            break
            ;;
		1)
            notification "Powering off in 10 seconds";
            sleep 20;
            reboot;
			break
			;;
		2)
            notification " Powering off in 20 seconds";
            sleep 20;
            poweroff;
			break
			;;
		3)
            notification " Locking in  5 seconds";
            # sleep 5;
            # i3lock-fancy;
            my-lock-screen.sh
			break
			;;
    esac
}
main
